CREATE TABLE EMPLOYEE(
ID int(10) NOT NULL AUTO_INCREMENT,
NOM varchar(50) NOT NULL,
PRENOM varchar(50) NOT NULL,
NAISSANCE varchar(50) NOT NULL,
ANCIENNETE int(10) NOT NULL,
PRIMARY KEY (ID)
FOREIGN KEY(DEPARTEMENT_ID) references DEPARTEMENT(ID)
);

CREATE TABLE DEPARTEMENT(
ID int(10) NOT NULL AUTO_INCREMENT,
NOM varchar(50) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO DEPARTEMENT(ID,NOM) VALUES
(1, 'RH')
(2, 'DEV');